<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\FiaPaymentConfirmation;
use App\Models\FiaPaymentRecord;

class FiaPaymentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $members = [
            [
                'member_id' => 'PRM2',
                'name' => 'Emmanuel Elioth Lulandala',
                'type' => 'PRM',
                'email' => 'emmanuel.lulandala@feedtan.co.tz',
                'gawio_la_fia' => 195851.65,
                'fia_iliyokomaa' => 0,
                'jumla' => 195851.65,
                'malipo_vya_vipande' => null,
                'loan' => null,
                'kiasi_baki' => 195851.65,
            ],
            [
                'member_id' => 'FND1',
                'name' => 'Mary Mwinuka',
                'type' => 'FND',
                'email' => 'mary.mwinuka@feedtan.co.tz',
                'gawio_la_fia' => 45000.00,
                'fia_iliyokomaa' => 1000000.00,
                'jumla' => 1045000.00,
                'malipo_vya_vipande' => null,
                'loan' => '45000.00',
                'kiasi_baki' => 1000000.00,
            ],
            [
                'member_id' => 'PRM1',
                'name' => 'Kanti Ambrose Kimario',
                'type' => 'PRM',
                'email' => 'kanti.kimario@feedtan.co.tz',
                'gawio_la_fia' => 90000.00,
                'fia_iliyokomaa' => 2000000.00,
                'jumla' => 2090000.00,
                'malipo_vya_vipande' => null,
                'loan' => null,
                'kiasi_baki' => 2090000.00,
            ],
            [
                'member_id' => 'ORD7',
                'name' => 'Kulwa Mwita Mang\'ana',
                'type' => 'ORD',
                'email' => 'kulwa.mangana@feedtan.co.tz',
                'gawio_la_fia' => 95000.00,
                'fia_iliyokomaa' => 0,
                'jumla' => 95000.00,
                'malipo_vya_vipande' => null,
                'loan' => '95000.00',
                'kiasi_baki' => 0.00,
            ],
            [
                'member_id' => 'ORD10',
                'name' => 'Arkelaus Kailembo',
                'type' => 'ORD',
                'email' => 'arkelaus.kailembo@feedtan.co.tz',
                'gawio_la_fia' => 55000.00,
                'fia_iliyokomaa' => 0,
                'jumla' => 55000.00,
                'malipo_vya_vipande' => null,
                'loan' => null,
                'kiasi_baki' => 55000.00,
            ],
            [
                'member_id' => 'PRM4',
                'name' => 'Living Christopher koka',
                'type' => 'PRM',
                'email' => 'living.koka@feedtan.co.tz',
                'gawio_la_fia' => 110000.00,
                'fia_iliyokomaa' => 0,
                'jumla' => 110000.00,
                'malipo_vya_vipande' => null,
                'loan' => null,
                'kiasi_baki' => 110000.00,
            ],
            [
                'member_id' => 'ORD2',
                'name' => 'Christina Maeda',
                'type' => 'ORD',
                'email' => 'christina.maeda@feedtan.co.tz',
                'gawio_la_fia' => 45000.00,
                'fia_iliyokomaa' => 1000000.00,
                'jumla' => 1045000.00,
                'malipo_vya_vipande' => null,
                'loan' => null,
                'kiasi_baki' => 1045000.00,
            ],
            [
                'member_id' => 'ORD5',
                'name' => 'Victoria S.Mwambungu',
                'type' => 'ORD',
                'email' => 'victoria.mwambungu@feedtan.co.tz',
                'gawio_la_fia' => 125000.00,
                'fia_iliyokomaa' => 0,
                'jumla' => 125000.00,
                'malipo_vya_vipande' => null,
                'loan' => null,
                'kiasi_baki' => 125000.00,
            ],
            [
                'member_id' => 'PRM5',
                'name' => 'Erick Buberwa',
                'type' => 'PRM',
                'email' => 'erick.buberwa@feedtan.co.tz',
                'gawio_la_fia' => 55000.00,
                'fia_iliyokomaa' => 0,
                'jumla' => 55000.00,
                'malipo_vya_vipande' => null,
                'loan' => null,
                'kiasi_baki' => 55000.00,
            ],
            [
                'member_id' => 'ASC9',
                'name' => 'Erick Anselim Minde',
                'type' => 'ASC',
                'email' => 'erick.minde@feedtan.co.tz',
                'gawio_la_fia' => 55000.00,
                'fia_iliyokomaa' => 0,
                'jumla' => 55000.00,
                'malipo_vya_vipande' => null,
                'loan' => null,
                'kiasi_baki' => 55000.00,
            ],
            [
                'member_id' => 'ASC13',
                'name' => 'Winnrose Elifuraha Mmari',
                'type' => 'ASC',
                'email' => 'winnrose.mmari@feedtan.co.tz',
                'gawio_la_fia' => 55000.00,
                'fia_iliyokomaa' => 0,
                'jumla' => 55000.00,
                'malipo_vya_vipande' => null,
                'loan' => null,
                'kiasi_baki' => 55000.00,
            ],
            [
                'member_id' => 'ASC1',
                'name' => 'Albert Sylvester Nkuhi',
                'type' => 'ASC',
                'email' => 'albert.nkuhi@feedtan.co.tz',
                'gawio_la_fia' => 55000.00,
                'fia_iliyokomaa' => 0,
                'jumla' => 55000.00,
                'malipo_vya_vipande' => null,
                'loan' => null,
                'kiasi_baki' => 55000.00,
            ],
            [
                'member_id' => 'ASC12',
                'name' => 'Aurelia Issack',
                'type' => 'ASC',
                'email' => 'aurelia.issack@feedtan.co.tz',
                'gawio_la_fia' => 115000.00,
                'fia_iliyokomaa' => 0,
                'jumla' => 115000.00,
                'malipo_vya_vipande' => null,
                'loan' => null,
                'kiasi_baki' => 115000.00,
            ],
            [
                'member_id' => 'ASC11',
                'name' => 'Hamisi Amiri Hasani',
                'type' => 'ASC',
                'email' => 'hamisi.hasani@feedtan.co.tz',
                'gawio_la_fia' => 55000.00,
                'fia_iliyokomaa' => 0,
                'jumla' => 55000.00,
                'malipo_vya_vipande' => null,
                'loan' => null,
                'kiasi_baki' => 55000.00,
            ],
            [
                'member_id' => 'SCH2',
                'name' => 'Sigfred A Ngereza',
                'type' => 'SCH',
                'email' => 'sigfred.ngereza@feedtan.co.tz',
                'gawio_la_fia' => 6888.89,
                'fia_iliyokomaa' => 0,
                'jumla' => 6888.89,
                'malipo_vya_vipande' => null,
                'loan' => null,
                'kiasi_baki' => 6888.89,
            ],
            [
                'member_id' => 'SCH10',
                'name' => 'Mwamini Osward Bavuma',
                'type' => 'SCH',
                'email' => 'mwamini.bavuma@feedtan.co.tz',
                'gawio_la_fia' => 8600.00,
                'fia_iliyokomaa' => 0,
                'jumla' => 8600.00,
                'malipo_vya_vipande' => null,
                'loan' => null,
                'kiasi_baki' => 8600.00,
            ],
            [
                'member_id' => 'ASC75',
                'name' => 'Caroline Ceasar Shija',
                'type' => 'ASC',
                'email' => 'caroline.shija@feedtan.co.tz',
                'gawio_la_fia' => 40000.00,
                'fia_iliyokomaa' => 0,
                'jumla' => 40000.00,
                'malipo_vya_vipande' => 40000.00,
                'loan' => null,
                'kiasi_baki' => 0.00,
            ],
            [
                'member_id' => 'SCH7',
                'name' => 'Eufomia Pancras Mshanga',
                'type' => 'SCH',
                'email' => 'eufomia.mshanga@feedtan.co.tz',
                'gawio_la_fia' => 9300.00,
                'fia_iliyokomaa' => 0,
                'jumla' => 9300.00,
                'malipo_vya_vipande' => null,
                'loan' => null,
                'kiasi_baki' => 9300.00,
            ],
            [
                'member_id' => 'ASC90',
                'name' => 'Anno Massawe',
                'type' => 'ASC',
                'email' => 'anno.massawe@feedtan.co.tz',
                'gawio_la_fia' => 1458333.33,
                'fia_iliyokomaa' => 0,
                'jumla' => 1458333.33,
                'malipo_vya_vipande' => null,
                'loan' => null,
                'kiasi_baki' => 1458333.33,
            ],
            [
                'member_id' => 'FND7',
                'name' => 'JAPHET METHUSELA MGEMA',
                'type' => 'FND',
                'email' => 'japhet.mgema@feedtan.co.tz',
                'gawio_la_fia' => 66703.30,
                'fia_iliyokomaa' => 0,
                'jumla' => 66703.30,
                'malipo_vya_vipande' => null,
                'loan' => null,
                'kiasi_baki' => 66703.30,
            ],
            [
                'member_id' => 'ASC122',
                'name' => 'Josephine Kiwelu',
                'type' => 'ASC',
                'email' => 'josephine.kiwelu@feedtan.co.tz',
                'gawio_la_fia' => 129000.00,
                'fia_iliyokomaa' => 0,
                'jumla' => 129000.00,
                'malipo_vya_vipande' => null,
                'loan' => null,
                'kiasi_baki' => 129000.00,
            ],
            [
                'member_id' => 'ASC119',
                'name' => 'ROBERT KIWIA',
                'type' => 'ASC',
                'email' => 'robert.kiwia@feedtan.co.tz',
                'gawio_la_fia' => 129000.00,
                'fia_iliyokomaa' => 0,
                'jumla' => 129000.00,
                'malipo_vya_vipande' => null,
                'loan' => null,
                'kiasi_baki' => 129000.00,
            ],
            [
                'member_id' => 'ASC107',
                'name' => 'Apolinari Elias Herman',
                'type' => 'ASC',
                'email' => 'apolinari.herman@feedtan.co.tz',
                'gawio_la_fia' => 10851.65,
                'fia_iliyokomaa' => 0,
                'jumla' => 10851.65,
                'malipo_vya_vipande' => null,
                'loan' => null,
                'kiasi_baki' => 10851.65,
            ],
            [
                'member_id' => 'SCH58',
                'name' => 'Neema Emmanuel Mria',
                'type' => 'SCH',
                'email' => 'neema.mria@feedtan.co.tz',
                'gawio_la_fia' => 5000.00,
                'fia_iliyokomaa' => 0,
                'jumla' => 5000.00,
                'malipo_vya_vipande' => null,
                'loan' => null,
                'kiasi_baki' => 5000.00,
            ],
            [
                'member_id' => 'FND2',
                'name' => 'Caesar Maulaga',
                'type' => 'FND',
                'email' => 'caesar.maulaga@feedtan.co.tz',
                'gawio_la_fia' => 24703.91,
                'fia_iliyokomaa' => 0,
                'jumla' => 24703.91,
                'malipo_vya_vipande' => 24703.91,
                'loan' => null,
                'kiasi_baki' => 0.00,
            ],
            [
                'member_id' => 'SCH69',
                'name' => 'Vicent Simon Gabriel',
                'type' => 'SCH',
                'email' => 'vicent.gabriel@feedtan.co.tz',
                'gawio_la_fia' => 1750.00,
                'fia_iliyokomaa' => 0,
                'jumla' => 1750.00,
                'malipo_vya_vipande' => null,
                'loan' => null,
                'kiasi_baki' => 1750.00,
            ],
            [
                'member_id' => 'ASC93',
                'name' => 'Lulu Ilomo',
                'type' => 'ASC',
                'email' => 'lulu.ilomo@feedtan.co.tz',
                'gawio_la_fia' => 0,
                'fia_iliyokomaa' => 0,
                'jumla' => 0,
                'malipo_vya_vipande' => null,
                'loan' => null,
                'kiasi_baki' => 1510.99,
            ],
            [
                'member_id' => 'ASC131',
                'name' => 'Petro Ngalu',
                'type' => 'ASC',
                'email' => 'petro.ngalu@feedtan.co.tz',
                'gawio_la_fia' => 2962.76,
                'fia_iliyokomaa' => 0,
                'jumla' => 2962.76,
                'malipo_vya_vipande' => null,
                'loan' => null,
                'kiasi_baki' => 2962.76,
            ],
        ];

        foreach ($members as $member) {
            // Create or update payment confirmation
            $confirmation = FiaPaymentConfirmation::updateOrCreate(
                ['member_id' => $member['member_id']],
                [
                    'member_name' => $member['name'],
                    'member_type' => $member['type'],
                    'member_email' => $member['email'],
                    'amount_to_pay' => $member['jumla'],
                    'status' => 'pending',
                    'notes' => 'Initial data import from seeder'
                ]
            );

            // Create or update payment record
            FiaPaymentRecord::updateOrCreate(
                ['member_id' => $member['member_id']],
                [
                    'gawio_la_fia' => $member['gawio_la_fia'],
                    'fia_iliyokomaa' => $member['fia_iliyokomaa'],
                    'jumla' => $member['jumla'],
                    'malipo_vya_vipande' => $member['malipo_vya_vipande'],
                    'loan' => $member['loan'],
                    'kiasi_baki' => $member['kiasi_baki'],
                    'status' => 'pending',
                    'notes' => 'Initial data import from seeder'
                ]
            );
        }

        $this->command->info('FIA Payment data seeded successfully!');
    }
}
