<?php

return [

    'client' => [
        'model' => \App\Models\Client::class,
        'option_label' => 'name',
        'label' => 'Clients',
        'search' => ['name', 'email', 'company', 'phone'],
        'columns' => [
            ['key' => 'id', 'label' => 'ID'],
            ['key' => 'name', 'label' => 'Name'],
            ['key' => 'email', 'label' => 'Email'],
            ['key' => 'phone', 'label' => 'Phone'],
            ['key' => 'company', 'label' => 'Company'],
            ['key' => 'status', 'label' => 'Status'],
            ['key' => 'created_at', 'label' => 'Created'],
        ],
        'fields' => [
            ['name' => 'name', 'label' => 'Name', 'type' => 'text'],
            ['name' => 'email', 'label' => 'Email', 'type' => 'email'],
            ['name' => 'phone', 'label' => 'Phone', 'type' => 'text'],
            ['name' => 'company', 'label' => 'Company', 'type' => 'text'],
            ['name' => 'address', 'label' => 'Address', 'type' => 'textarea'],
            ['name' => 'city', 'label' => 'City', 'type' => 'text'],
            ['name' => 'country', 'label' => 'Country', 'type' => 'text'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'default' => 'active', 'options' => ['active' => 'Active', 'inactive' => 'Inactive', 'pending' => 'Pending']],
            ['name' => 'notes', 'label' => 'Notes', 'type' => 'textarea'],
        ],
        'rules' => [
            'name' => 'required',
            'email' => 'required|email',
            'status' => 'in:active,inactive,pending',
        ],
    ],

    'lead' => [
        'model' => \App\Models\DemoRequest::class,
        'option_label' => 'company_name',
        'label' => 'Leads',
        'search' => ['company_name', 'contact_person', 'email'],
        'columns' => [
            ['key' => 'id', 'label' => 'ID'],
            ['key' => 'company_name', 'label' => 'Company'],
            ['key' => 'contact_person', 'label' => 'Contact'],
            ['key' => 'email', 'label' => 'Email'],
            ['key' => 'demo_type', 'label' => 'Demo'],
            ['key' => 'preferred_date', 'label' => 'Date'],
            ['key' => 'urgency', 'label' => 'Urgency'],
            ['key' => 'status', 'label' => 'Status'],
        ],
        'fields' => [
            ['name' => 'demo_type', 'label' => 'Demo Type', 'type' => 'text'],
            ['name' => 'company_name', 'label' => 'Company', 'type' => 'text'],
            ['name' => 'contact_person', 'label' => 'Contact Person', 'type' => 'text'],
            ['name' => 'job_title', 'label' => 'Job Title', 'type' => 'text'],
            ['name' => 'email', 'label' => 'Email', 'type' => 'email'],
            ['name' => 'phone', 'label' => 'Phone', 'type' => 'text'],
            ['name' => 'country', 'label' => 'Country', 'type' => 'text'],
            ['name' => 'city', 'label' => 'City', 'type' => 'text'],
            ['name' => 'preferred_date', 'label' => 'Preferred Date', 'type' => 'date'],
            ['name' => 'preferred_time', 'label' => 'Preferred Time', 'type' => 'time'],
            ['name' => 'attendees', 'label' => 'Attendees', 'type' => 'text'],
            ['name' => 'language', 'label' => 'Language', 'type' => 'text'],
            ['name' => 'urgency', 'label' => 'Urgency', 'type' => 'select', 'default' => 'medium', 'options' => ['low' => 'Low', 'medium' => 'Medium', 'high' => 'High']],
            ['name' => 'message', 'label' => 'Message', 'type' => 'textarea'],
            ['name' => 'estimated_value', 'label' => 'Est. Value', 'type' => 'number', 'step' => '0.01'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'text', 'default' => 'pending'],
            ['name' => 'notes', 'label' => 'Notes', 'type' => 'textarea'],
        ],
        'rules' => [
            'demo_type' => 'required',
            'company_name' => 'required',
            'contact_person' => 'required',
            'email' => 'required|email',
            'phone' => 'required',
            'estimated_value' => 'nullable|numeric',
        ],
    ],

    'contact' => [
        'model' => \App\Models\ContactSubmission::class,
        'option_label' => 'name',
        'label' => 'Contacts',
        'search' => ['name', 'email', 'subject'],
        'columns' => [
            ['key' => 'id', 'label' => 'ID'],
            ['key' => 'name', 'label' => 'Name'],
            ['key' => 'email', 'label' => 'Email'],
            ['key' => 'subject', 'label' => 'Subject'],
            ['key' => 'status', 'label' => 'Status'],
            ['key' => 'created_at', 'label' => 'Created'],
        ],
        'fields' => [
            ['name' => 'name', 'label' => 'Name', 'type' => 'text'],
            ['name' => 'email', 'label' => 'Email', 'type' => 'email'],
            ['name' => 'phone', 'label' => 'Phone', 'type' => 'text'],
            ['name' => 'subject', 'label' => 'Subject', 'type' => 'text'],
            ['name' => 'message', 'label' => 'Message', 'type' => 'textarea'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'text', 'default' => 'new'],
            ['name' => 'notes', 'label' => 'Notes', 'type' => 'textarea'],
        ],
        'rules' => [
            'name' => 'required',
            'email' => 'required|email',
            'subject' => 'required',
            'message' => 'required',
        ],
    ],

    'project' => [
        'model' => \App\Models\Project::class,
        'label' => 'Projects',
        'search' => ['project_number', 'title'],
        'columns' => [
            ['key' => 'id', 'label' => 'ID'],
            ['key' => 'project_number', 'label' => 'Number'],
            ['key' => 'title', 'label' => 'Title'],
            ['key' => 'client_id', 'label' => 'Client', 'rel' => ['slug' => 'client', 'model' => \App\Models\Client::class, 'label' => 'name']],
            ['key' => 'service_type', 'label' => 'Service'],
            ['key' => 'price', 'label' => 'Price'],
            ['key' => 'status', 'label' => 'Status'],
            ['key' => 'progress_percentage', 'label' => 'Progress'],
        ],
        'fields' => [
            ['name' => 'project_number', 'label' => 'Project Number', 'type' => 'text'],
            ['name' => 'title', 'label' => 'Title', 'type' => 'text'],
            ['name' => 'description', 'label' => 'Description', 'type' => 'textarea'],
            ['name' => 'client_id', 'label' => 'Client', 'type' => 'select', 'relselect' => ['slug' => 'client', 'model' => \App\Models\Client::class, 'label' => 'name', 'value' => 'id']],
            ['name' => 'demo_request_id', 'label' => 'Demo Request', 'type' => 'select', 'relselect' => ['slug' => 'lead', 'model' => \App\Models\DemoRequest::class, 'label' => 'company_name', 'value' => 'id']],
            ['name' => 'service_type', 'label' => 'Service Type', 'type' => 'text'],
            ['name' => 'price', 'label' => 'Price', 'type' => 'number', 'step' => '0.01'],
            ['name' => 'currency', 'label' => 'Currency', 'type' => 'select', 'default' => 'TZS', 'options' => ['TZS' => 'TZS', 'USD' => 'USD', 'EUR' => 'EUR']],
            ['name' => 'start_date', 'label' => 'Start Date', 'type' => 'date'],
            ['name' => 'end_date', 'label' => 'End Date', 'type' => 'date'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'text', 'default' => 'pending'],
            ['name' => 'progress_percentage', 'label' => 'Progress %', 'type' => 'number', 'default' => 0],
            ['name' => 'current_stage', 'label' => 'Current Stage', 'type' => 'text', 'default' => 'pending'],
            ['name' => 'assigned_to', 'label' => 'Assigned To', 'type' => 'select', 'relselect' => ['slug' => 'user', 'model' => \App\Models\User::class, 'label' => 'name', 'value' => 'id']],
            ['name' => 'notes', 'label' => 'Notes', 'type' => 'textarea'],
        ],
        'rules' => [
            'project_number' => 'required',
            'title' => 'required',
            'description' => 'required',
            'service_type' => 'required',
            'price' => 'required|numeric',
            'start_date' => 'required|date',
            'end_date' => 'required|date',
        ],
    ],

    'service' => [
        'model' => \App\Models\Service::class,
        'option_label' => 'name',
        'label' => 'Services',
        'search' => ['name', 'category'],
        'columns' => [
            ['key' => 'id', 'label' => 'ID'],
            ['key' => 'name', 'label' => 'Name'],
            ['key' => 'category', 'label' => 'Category'],
            ['key' => 'base_price', 'label' => 'Base Price'],
            ['key' => 'status', 'label' => 'Status'],
        ],
        'fields' => [
            ['name' => 'name', 'label' => 'Name', 'type' => 'text'],
            ['name' => 'description', 'label' => 'Description', 'type' => 'textarea'],
            ['name' => 'category', 'label' => 'Category', 'type' => 'text'],
            ['name' => 'base_price', 'label' => 'Base Price', 'type' => 'number', 'step' => '0.01'],
            ['name' => 'icon', 'label' => 'Icon', 'type' => 'text'],
            ['name' => 'color', 'label' => 'Color', 'type' => 'text'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'default' => 'active', 'options' => ['active' => 'Active', 'inactive' => 'Inactive']],
            ['name' => 'features', 'label' => 'Features (one per line)', 'type' => 'json'],
            ['name' => 'estimated_days', 'label' => 'Est. Days', 'type' => 'number'],
        ],
        'rules' => [
            'name' => 'required',
            'description' => 'required',
            'category' => 'required',
        ],
    ],

    'package' => [
        'model' => \App\Models\Package::class,
        'option_label' => 'name',
        'label' => 'Packages',
        'search' => ['name'],
        'columns' => [
            ['key' => 'id', 'label' => 'ID'],
            ['key' => 'name', 'label' => 'Name'],
            ['key' => 'service_id', 'label' => 'Service', 'rel' => ['slug' => 'service', 'model' => \App\Models\Service::class, 'label' => 'name']],
            ['key' => 'price', 'label' => 'Price'],
            ['key' => 'status', 'label' => 'Status'],
            ['key' => 'sort_order', 'label' => 'Order'],
        ],
        'fields' => [
            ['name' => 'service_id', 'label' => 'Service', 'type' => 'select', 'relselect' => ['slug' => 'service', 'model' => \App\Models\Service::class, 'label' => 'name', 'value' => 'id']],
            ['name' => 'name', 'label' => 'Name', 'type' => 'text'],
            ['name' => 'description', 'label' => 'Description', 'type' => 'textarea'],
            ['name' => 'price', 'label' => 'Price', 'type' => 'number', 'step' => '0.01'],
            ['name' => 'duration', 'label' => 'Duration', 'type' => 'text'],
            ['name' => 'features', 'label' => 'Features (one per line)', 'type' => 'json'],
            ['name' => 'icon', 'label' => 'Icon', 'type' => 'text'],
            ['name' => 'color', 'label' => 'Color', 'type' => 'text'],
            ['name' => 'is_popular', 'label' => 'Popular', 'type' => 'checkbox', 'default' => 0],
            ['name' => 'status', 'label' => 'Status', 'type' => 'text', 'default' => 'active'],
            ['name' => 'sort_order', 'label' => 'Sort Order', 'type' => 'number', 'default' => 0],
        ],
        'rules' => [
            'name' => 'required',
            'price' => 'required|numeric',
        ],
    ],

    'pricing' => [
        'model' => \App\Models\PricingPlan::class,
        'option_label' => 'name',
        'label' => 'Pricing Plans',
        'search' => ['name'],
        'columns' => [
            ['key' => 'id', 'label' => 'ID'],
            ['key' => 'name', 'label' => 'Name'],
            ['key' => 'price', 'label' => 'Price'],
            ['key' => 'billing_cycle', 'label' => 'Cycle'],
            ['key' => 'currency', 'label' => 'Currency'],
            ['key' => 'is_active', 'label' => 'Active'],
            ['key' => 'sort_order', 'label' => 'Order'],
        ],
        'fields' => [
            ['name' => 'name', 'label' => 'Name', 'type' => 'text'],
            ['name' => 'description', 'label' => 'Description', 'type' => 'textarea'],
            ['name' => 'price', 'label' => 'Price', 'type' => 'number', 'step' => '0.01'],
            ['name' => 'billing_cycle', 'label' => 'Billing Cycle', 'type' => 'text'],
            ['name' => 'features', 'label' => 'Features (one per line)', 'type' => 'json'],
            ['name' => 'currency', 'label' => 'Currency', 'type' => 'select', 'default' => 'USD', 'options' => ['USD' => 'USD', 'EUR' => 'EUR', 'TZS' => 'TZS']],
            ['name' => 'is_active', 'label' => 'Active', 'type' => 'checkbox', 'default' => 1],
            ['name' => 'sort_order', 'label' => 'Sort Order', 'type' => 'number', 'default' => 0],
            ['name' => 'stripe_price_id', 'label' => 'Stripe Price ID', 'type' => 'text'],
        ],
        'rules' => [
            'name' => 'required',
            'description' => 'required',
            'price' => 'required|numeric',
            'billing_cycle' => 'required',
        ],
    ],

    'offer' => [
        'model' => \App\Models\Offer::class,
        'label' => 'Offers',
        'search' => ['name', 'code'],
        'columns' => [
            ['key' => 'id', 'label' => 'ID'],
            ['key' => 'name', 'label' => 'Name'],
            ['key' => 'code', 'label' => 'Code'],
            ['key' => 'discount_type', 'label' => 'Type'],
            ['key' => 'discount_value', 'label' => 'Value'],
            ['key' => 'is_active', 'label' => 'Active'],
            ['key' => 'valid_until', 'label' => 'Valid Until'],
        ],
        'fields' => [
            ['name' => 'name', 'label' => 'Name', 'type' => 'text'],
            ['name' => 'description', 'label' => 'Description', 'type' => 'textarea'],
            ['name' => 'code', 'label' => 'Code', 'type' => 'text'],
            ['name' => 'discount_type', 'label' => 'Discount Type', 'type' => 'select', 'options' => ['percentage' => 'Percentage', 'fixed' => 'Fixed']],
            ['name' => 'discount_value', 'label' => 'Discount Value', 'type' => 'number', 'step' => '0.01'],
            ['name' => 'min_purchase', 'label' => 'Min Purchase', 'type' => 'number', 'step' => '0.01'],
            ['name' => 'max_discount', 'label' => 'Max Discount', 'type' => 'number', 'step' => '0.01'],
            ['name' => 'usage_limit', 'label' => 'Usage Limit', 'type' => 'number'],
            ['name' => 'valid_from', 'label' => 'Valid From', 'type' => 'datetime-local'],
            ['name' => 'valid_until', 'label' => 'Valid Until', 'type' => 'datetime-local'],
            ['name' => 'is_active', 'label' => 'Active', 'type' => 'checkbox', 'default' => 1],
            ['name' => 'applicable_services', 'label' => 'Applicable Services (one per line)', 'type' => 'json'],
        ],
        'rules' => [
            'name' => 'required',
            'description' => 'required',
            'code' => 'required',
            'discount_type' => 'required|in:percentage,fixed',
            'discount_value' => 'required|numeric',
        ],
    ],

    'booking' => [
        'model' => \App\Models\PackageOrder::class,
        'option_label' => 'order_number',
        'label' => 'Bookings',
        'search' => ['order_number', 'client_name', 'client_email'],
        'columns' => [
            ['key' => 'id', 'label' => 'ID'],
            ['key' => 'order_number', 'label' => 'Order #'],
            ['key' => 'client_name', 'label' => 'Client'],
            ['key' => 'client_email', 'label' => 'Email'],
            ['key' => 'service_id', 'label' => 'Service', 'rel' => ['slug' => 'service', 'model' => \App\Models\Service::class, 'label' => 'name']],
            ['key' => 'package_id', 'label' => 'Package', 'rel' => ['slug' => 'package', 'model' => \App\Models\Package::class, 'label' => 'name']],
            ['key' => 'total_price', 'label' => 'Total'],
            ['key' => 'status', 'label' => 'Status'],
        ],
        'fields' => [
            ['name' => 'order_number', 'label' => 'Order Number', 'type' => 'text'],
            ['name' => 'client_name', 'label' => 'Client Name', 'type' => 'text'],
            ['name' => 'client_email', 'label' => 'Client Email', 'type' => 'email'],
            ['name' => 'client_phone', 'label' => 'Client Phone', 'type' => 'text'],
            ['name' => 'company_name', 'label' => 'Company', 'type' => 'text'],
            ['name' => 'service_id', 'label' => 'Service', 'type' => 'select', 'relselect' => ['slug' => 'service', 'model' => \App\Models\Service::class, 'label' => 'name', 'value' => 'id']],
            ['name' => 'package_id', 'label' => 'Package', 'type' => 'select', 'relselect' => ['slug' => 'package', 'model' => \App\Models\Package::class, 'label' => 'name', 'value' => 'id']],
            ['name' => 'selected_features', 'label' => 'Selected Features (one per line)', 'type' => 'json'],
            ['name' => 'selected_addons', 'label' => 'Selected Addons (one per line)', 'type' => 'json'],
            ['name' => 'total_price', 'label' => 'Total Price', 'type' => 'number', 'step' => '0.01'],
            ['name' => 'advance_payment', 'label' => 'Advance Payment', 'type' => 'number', 'step' => '0.01'],
            ['name' => 'remaining_balance', 'label' => 'Remaining Balance', 'type' => 'number', 'step' => '0.01'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'text', 'default' => 'pending'],
            ['name' => 'payment_reference', 'label' => 'Payment Reference', 'type' => 'text'],
            ['name' => 'payment_status', 'label' => 'Payment Status', 'type' => 'text'],
            ['name' => 'payment_plan', 'label' => 'Payment Plan', 'type' => 'text'],
            ['name' => 'timeline_priority', 'label' => 'Timeline Priority', 'type' => 'text'],
            ['name' => 'notes', 'label' => 'Notes', 'type' => 'textarea'],
        ],
        'rules' => [
            'order_number' => 'required',
            'client_name' => 'required',
            'client_email' => 'required|email',
            'client_phone' => 'required',
            'total_price' => 'required|numeric',
            'advance_payment' => 'required|numeric',
            'remaining_balance' => 'required|numeric',
        ],
    ],

    'invoice' => [
        'model' => \App\Models\Invoice::class,
        'label' => 'Invoices',
        'search' => ['invoice_number', 'client_name', 'client_email'],
        'columns' => [
            ['key' => 'id', 'label' => 'ID'],
            ['key' => 'invoice_number', 'label' => 'Invoice #'],
            ['key' => 'client_name', 'label' => 'Client'],
            ['key' => 'client_email', 'label' => 'Email'],
            ['key' => 'amount', 'label' => 'Amount'],
            ['key' => 'total', 'label' => 'Total'],
            ['key' => 'status', 'label' => 'Status'],
            ['key' => 'due_date', 'label' => 'Due'],
        ],
        'fields' => [
            ['name' => 'invoice_number', 'label' => 'Invoice Number', 'type' => 'text'],
            ['name' => 'demo_request_id', 'label' => 'Demo Request', 'type' => 'select', 'relselect' => ['slug' => 'lead', 'model' => \App\Models\DemoRequest::class, 'label' => 'company_name', 'value' => 'id']],
            ['name' => 'order_id', 'label' => 'Booking', 'type' => 'select', 'relselect' => ['slug' => 'booking', 'model' => \App\Models\PackageOrder::class, 'label' => 'order_number', 'value' => 'id']],
            ['name' => 'client_name', 'label' => 'Client Name', 'type' => 'text'],
            ['name' => 'client_email', 'label' => 'Client Email', 'type' => 'email'],
            ['name' => 'client_phone', 'label' => 'Client Phone', 'type' => 'text'],
            ['name' => 'description', 'label' => 'Description', 'type' => 'textarea'],
            ['name' => 'amount', 'label' => 'Amount', 'type' => 'number', 'step' => '0.01'],
            ['name' => 'tax', 'label' => 'Tax', 'type' => 'number', 'step' => '0.01', 'default' => 0],
            ['name' => 'total', 'label' => 'Total', 'type' => 'number', 'step' => '0.01'],
            ['name' => 'due_date', 'label' => 'Due Date', 'type' => 'date'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'text', 'default' => 'pending'],
            ['name' => 'payment_method', 'label' => 'Payment Method', 'type' => 'text'],
            ['name' => 'paid_date', 'label' => 'Paid Date', 'type' => 'date'],
            ['name' => 'notes', 'label' => 'Notes', 'type' => 'textarea'],
        ],
        'rules' => [
            'invoice_number' => 'required',
            'client_name' => 'required',
            'client_email' => 'required|email',
            'description' => 'required',
            'amount' => 'required|numeric',
            'total' => 'required|numeric',
            'due_date' => 'required|date',
        ],
    ],

    'expense' => [
        'model' => \App\Models\Expense::class,
        'label' => 'Expenses',
        'search' => ['expense_number', 'category', 'description'],
        'columns' => [
            ['key' => 'id', 'label' => 'ID'],
            ['key' => 'expense_number', 'label' => 'Expense #'],
            ['key' => 'category', 'label' => 'Category'],
            ['key' => 'amount', 'label' => 'Amount'],
            ['key' => 'expense_date', 'label' => 'Date'],
            ['key' => 'status', 'label' => 'Status'],
        ],
        'fields' => [
            ['name' => 'expense_number', 'label' => 'Expense Number', 'type' => 'text'],
            ['name' => 'category', 'label' => 'Category', 'type' => 'text'],
            ['name' => 'description', 'label' => 'Description', 'type' => 'text'],
            ['name' => 'amount', 'label' => 'Amount', 'type' => 'number', 'step' => '0.01'],
            ['name' => 'expense_date', 'label' => 'Expense Date', 'type' => 'date'],
            ['name' => 'payment_method', 'label' => 'Payment Method', 'type' => 'text'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'text', 'default' => 'pending'],
            ['name' => 'approved_by', 'label' => 'Approved By', 'type' => 'select', 'relselect' => ['slug' => 'user', 'model' => \App\Models\User::class, 'label' => 'name', 'value' => 'id']],
            ['name' => 'receipt_url', 'label' => 'Receipt URL', 'type' => 'text'],
            ['name' => 'notes', 'label' => 'Notes', 'type' => 'textarea'],
        ],
        'rules' => [
            'expense_number' => 'required',
            'category' => 'required',
            'description' => 'required',
            'amount' => 'required|numeric',
            'expense_date' => 'required|date',
            'payment_method' => 'required',
        ],
    ],

    'message' => [
        'model' => \App\Models\Message::class,
        'label' => 'Messages',
        'search' => ['name', 'email', 'subject'],
        'columns' => [
            ['key' => 'id', 'label' => 'ID'],
            ['key' => 'name', 'label' => 'Name'],
            ['key' => 'email', 'label' => 'Email'],
            ['key' => 'subject', 'label' => 'Subject'],
            ['key' => 'status', 'label' => 'Status'],
            ['key' => 'priority', 'label' => 'Priority'],
        ],
        'fields' => [
            ['name' => 'name', 'label' => 'Name', 'type' => 'text'],
            ['name' => 'email', 'label' => 'Email', 'type' => 'email'],
            ['name' => 'phone', 'label' => 'Phone', 'type' => 'text'],
            ['name' => 'subject', 'label' => 'Subject', 'type' => 'text'],
            ['name' => 'message', 'label' => 'Message', 'type' => 'textarea'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'default' => 'new', 'options' => ['new' => 'New', 'in-progress' => 'In Progress', 'resolved' => 'Resolved', 'closed' => 'Closed']],
            ['name' => 'priority', 'label' => 'Priority', 'type' => 'select', 'default' => 'medium', 'options' => ['low' => 'Low', 'medium' => 'Medium', 'high' => 'High', 'urgent' => 'Urgent']],
            ['name' => 'assigned_to', 'label' => 'Assigned To', 'type' => 'select', 'relselect' => ['slug' => 'user', 'model' => \App\Models\User::class, 'label' => 'name', 'value' => 'id']],
            ['name' => 'notes', 'label' => 'Notes', 'type' => 'textarea'],
        ],
        'rules' => [
            'name' => 'required',
            'email' => 'required|email',
            'subject' => 'required',
            'message' => 'required',
            'status' => 'in:new,in-progress,resolved,closed',
            'priority' => 'in:low,medium,high,urgent',
        ],
    ],

    'user' => [
        'model' => \App\Models\User::class,
        'option_label' => 'name',
        'label' => 'Team',
        'search' => ['name', 'email'],
        'columns' => [
            ['key' => 'id', 'label' => 'ID'],
            ['key' => 'name', 'label' => 'Name'],
            ['key' => 'email', 'label' => 'Email'],
            ['key' => 'created_at', 'label' => 'Created'],
        ],
        'fields' => [
            ['name' => 'name', 'label' => 'Name', 'type' => 'text'],
            ['name' => 'email', 'label' => 'Email', 'type' => 'email'],
            ['name' => 'password', 'label' => 'Password', 'type' => 'password'],
        ],
        'rules' => [
            'name' => 'required',
            'email' => 'required|email',
        ],
    ],

    'file' => [
        'model' => \App\Models\FileManager::class,
        'option_label' => 'filename',
        'label' => 'Files',
        'search' => ['filename', 'original_name', 'category'],
        'columns' => [
            ['key' => 'id', 'label' => 'ID'],
            ['key' => 'filename', 'label' => 'Filename'],
            ['key' => 'original_name', 'label' => 'Original'],
            ['key' => 'category', 'label' => 'Category'],
            ['key' => 'is_folder', 'label' => 'Folder'],
            ['key' => 'is_public', 'label' => 'Public'],
            ['key' => 'uploaded_by', 'label' => 'Uploaded By', 'rel' => ['slug' => 'user', 'model' => \App\Models\User::class, 'label' => 'name']],
        ],
        'fields' => [
            ['name' => 'parent_id', 'label' => 'Parent Folder', 'type' => 'select', 'relselect' => ['slug' => 'file', 'model' => \App\Models\FileManager::class, 'label' => 'filename', 'value' => 'id']],
            ['name' => 'filename', 'label' => 'Filename', 'type' => 'text'],
            ['name' => 'original_name', 'label' => 'Original Name', 'type' => 'text'],
            ['name' => 'mime_type', 'label' => 'MIME Type', 'type' => 'text'],
            ['name' => 'file_path', 'label' => 'File Path', 'type' => 'text'],
            ['name' => 'file_size', 'label' => 'File Size', 'type' => 'text'],
            ['name' => 'category', 'label' => 'Category', 'type' => 'text', 'default' => 'general'],
            ['name' => 'folder_path', 'label' => 'Folder Path', 'type' => 'text'],
            ['name' => 'is_folder', 'label' => 'Is Folder', 'type' => 'checkbox', 'default' => 0],
            ['name' => 'description', 'label' => 'Description', 'type' => 'textarea'],
            ['name' => 'uploaded_by', 'label' => 'Uploaded By', 'type' => 'select', 'relselect' => ['slug' => 'user', 'model' => \App\Models\User::class, 'label' => 'name', 'value' => 'id']],
            ['name' => 'is_public', 'label' => 'Public', 'type' => 'checkbox', 'default' => 0],
        ],
        'rules' => [
            'filename' => 'required',
            'original_name' => 'required',
            'mime_type' => 'required',
            'file_path' => 'required',
            'file_size' => 'required',
        ],
    ],

];
