<?php

return [
    'blog_posts' => [
        [
            'slug' => 'web-development-trends-tanzania-2026',
            'title' => 'Top Web Development Trends for Tanzanian Businesses in 2026',
            'excerpt' => 'Composable stacks, performance budgets, and mobile-money-first UX are reshaping how East African brands ship digital products.',
            'category' => 'Web Development',
            'category_color' => '#1a6fc4',
            'date' => '2026-05-02',
            'reading_minutes' => 7,
            'image' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600083/programming-background-with-person-working-with-codes-computer_f8umdv.jpg',
            'paragraphs' => [
                'Teams across Tanzania are prioritizing Lighthouse performance, structured content models, and resilient hosting footprints that survive intermittent connectivity.',
                'Mobile money remains the conversion backbone—checkout flows that preload operators (M‑Pesa, TigoPesa, AzamPesa) and expose deep links reduce abandoned carts dramatically.',
                'Composable architectures let marketers iterate without redeploying the entire stack, keeping safari operators agile during seasonality spikes.',
            ],
        ],
        [
            'slug' => 'cyber-threat-landscape-tz-smes',
            'title' => 'How SMEs in Tanzania Should Prioritize Cyber Defense',
            'excerpt' => 'Start with asset inventory, segmented Wi‑Fi, and realistic tabletop exercises before chasing shiny tools.',
            'category' => 'Cybersecurity',
            'category_color' => '#dc2626',
            'date' => '2026-04-28',
            'reading_minutes' => 6,
            'image' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600081/criminal-hacking-system-unsuccessfully_jjxzdq.jpg',
            'paragraphs' => [
                'Most breaches we remediate still stem from reused VPN passwords and flat networks—fix segmentation before buying another appliance.',
                'Weekly backups tested via restores outperform glossy “immutable” marketing slides when ransomware strikes at month-end closing.',
                'Align monitoring alerts to business hours in East Africa Time so on-call rotations stay humane while staying compliant with regulator expectations.',
            ],
        ],
        [
            'slug' => 'hospitality-network-design-best-practices',
            'title' => 'Designing Guest‑Grade Networks for Lodges & Camps',
            'excerpt' => 'Separate VLANs, captive portals, and proactive RF surveys keep hospitality brands review‑worthy.',
            'category' => 'Networking',
            'category_color' => '#10b981',
            'date' => '2026-04-22',
            'reading_minutes' => 8,
            'image' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600083/network-switch-with-cables_btxlxw.jpg',
            'paragraphs' => [
                'Start every engagement with a predictive survey—not guesswork—especially when stone walls and safari tents skew attenuation.',
                'Guest SSIDs should never share broadcast domains with POS or CCTV backhauls; micro‑segmentation saves incident response time.',
                'Automated SMS alerts on WAN failover mean lodge managers wake up to actionable context instead of angry TripAdvisor screenshots.',
            ],
        ],
        [
            'slug' => 'mobile-apps-customer-retention-2026',
            'title' => 'Why Tanzanian Brands Win Retention with Mobile Apps',
            'excerpt' => 'Offline caches, proactive push journeys, and ledger‑grade payments anchor loyalty beyond landing pages.',
            'category' => 'Mobile Apps',
            'category_color' => '#8b5cf6',
            'date' => '2026-04-18',
            'reading_minutes' => 5,
            'image' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600084/i-m-hungry-hands-man-looking-food-delivery-app-his-smartphone-ordering-dinner-online_igrjev.jpg',
            'paragraphs' => [
                'Flutter and React Native parity cuts dual‑team overhead while keeping parity with platform‑specific payment SDK expectations.',
                'Behavioral cohorts powered by local SMS gateways outperform expensive foreign ESPs when bandwidth budgets are tight.',
                'Ship incremental releases tied to analytics experiments—not yearly big bangs—to learn from Dar es Salaam and Arusha cohort differences.',
            ],
        ],
        [
            'slug' => 'cloud-cost-controls-tanzanian-smes',
            'title' => 'Cloud Economics: Rightsizing Workloads for Tanzanian SMEs',
            'excerpt' => 'Reserved capacity, egress discipline, and tagging hygiene beat generic lift‑and‑shift quotes.',
            'category' => 'Cloud Services',
            'category_color' => '#3b82f6',
            'date' => '2026-04-12',
            'reading_minutes' => 6,
            'image' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600082/modern-data-center-providing-cloud-services-enabling-businesses-access-computing-resources-storage-demand-internet-server-room-infrastructure-3d-render-animation_lljtml.jpg',
            'paragraphs' => [
                'Finance teams want amortization clarity—tie each cloud invoice line to a department tag before auditors ask.',
                'Burst workloads belong on serverless hooks; steady ERP replicas deserve predictable VMs with backup snapshots cross‑region.',
                'Monthly checkpoints comparing USD invoices against TZS budgets avoid unpleasant FX surprises.',
            ],
        ],
        [
            'slug' => 'proactive-it-support-playbook',
            'title' => 'Proactive IT Support Beats Break‑Fix Every Time',
            'excerpt' => 'Telemetry on endpoints, patch calendars, and WhatsApp bridges shorten MTTR for distributed teams.',
            'category' => 'IT Support',
            'category_color' => '#f59e0b',
            'date' => '2026-04-09',
            'reading_minutes' => 5,
            'image' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600078/admin-data-center-typing-notebook-keyboard-using-automation-tools_lsc29m.jpg',
            'paragraphs' => [
                'Automated patching windows aligned with payroll deadlines reduce helpdesk chaos.',
                'SMS‑first ticketing respects how NGO field teams actually collaborate.',
                'Quarterly resilience drills simulate ISP outages so failover routes stay warm—not theoretical.',
            ],
        ],
        [
            'slug' => 'mpesa-api-integration-checklist',
            'title' => 'Checklist: Shipping Reliable Mobile Money APIs',
            'excerpt' => 'Idempotency keys, reconciliation jobs, and sandbox parity save launch weekends.',
            'category' => 'Web Development',
            'category_color' => '#1a6fc4',
            'date' => '2026-04-05',
            'reading_minutes' => 7,
            'image' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600083/showing-cart-trolley-shopping-online-sign-graphic_j4fy9u.jpg',
            'paragraphs' => [
                'Webhook retries must be deduplicated—store gateway references with unique indexes.',
                'User‑visible failures deserve Swahili microcopy plus WhatsApp escalation paths.',
                'Nightly reconciliation spreadsheets are not optional when regulators request audit trails.',
            ],
        ],
        [
            'slug' => 'data-sovereignty-east-africa',
            'title' => 'Data Sovereignty Conversations Every CTO Should Own',
            'excerpt' => 'Understand residency commitments, subprocessors, and encryption scopes before signing SaaS agreements.',
            'category' => 'ICT Strategy',
            'category_color' => '#0f766e',
            'date' => '2026-03-30',
            'reading_minutes' => 6,
            'image' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600082/modern-data-center-providing-cloud-services-enabling-businesses-access-computing-resources-storage-demand-internet-server-room-infrastructure-3d-render-animation_lljtml.jpg',
            'paragraphs' => [
                'Map regulated datasets (payroll, health, telco metadata) to concrete storage regions—not marketing PDFs.',
                'Bring legal and infra leads into the same workshop; ambiguous DPAs become operational runbooks.',
                'Document breach notification timelines in EAT to avoid scrambling during holidays.',
            ],
        ],
        [
            'slug' => 'wifi-security-for-remote-teams',
            'title' => 'Securing Home Wi‑Fi for Distributed Tanzanian Teams',
            'excerpt' => 'Hardware swaps, WPA3, and DNS filtering raise the floor against credential stuffing.',
            'category' => 'Cybersecurity',
            'category_color' => '#dc2626',
            'date' => '2026-03-24',
            'reading_minutes' => 4,
            'image' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600083/network-switch-with-cables_btxlxw.jpg',
            'paragraphs' => [
                'Issue corporate VPN profiles instead of trusting residential ISP routers blindly.',
                'DNS filtering blocks phishing kits targeting payroll portals common during bonus season.',
                'Quarterly reminders to rotate IoT passwords prevent Mirai‑style noise from impacting Zoom calls.',
            ],
        ],
        [
            'slug' => 'analytics-for-tour-operators',
            'title' => 'Analytics Dashboards Tour Operators Actually Use',
            'excerpt' => 'Connect CRM stages, ad spend, and mobile money settlements into one nightly rollup.',
            'category' => 'Data & Analytics',
            'category_color' => '#ea580c',
            'date' => '2026-03-18',
            'reading_minutes' => 6,
            'image' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600083/programming-background-with-person-working-with-codes-computer_f8umdv.jpg',
            'paragraphs' => [
                'Stop exporting CSVs manually—schedule transforms into Looker or Metabase with TZ timezone baked in.',
                'Attribute conversions back to WhatsApp threads using UTMs embedded in wa.me links.',
                'Alert teams when cost‑per‑lead spikes post‑algorithm updates.',
            ],
        ],
        [
            'slug' => 'iot-sensors-field-operations',
            'title' => 'IoT Telemetry Without Overengineering Your Stack',
            'excerpt' => 'MQTT brokers at the edge plus lightweight dashboards beat premature Kubernetes clusters.',
            'category' => 'Networking',
            'category_color' => '#10b981',
            'date' => '2026-03-10',
            'reading_minutes' => 5,
            'image' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600079/beautiful-optical-fiber-detail_wck3wq.jpg',
            'paragraphs' => [
                'Battery‑powered sensors need solar failover plans documented ahead of rainy seasons.',
                'Backhaul over LTE? negotiate QoS with carriers before deploying hundreds of nodes.',
                'Use Grafana alerts routed to SMS when WAN latency crosses SLA thresholds.',
            ],
        ],
        [
            'slug' => 'digital-transformation-roadmaps',
            'title' => 'Building ICT Roadmaps Leadership Will Fund',
            'excerpt' => 'Start with measurable KPIs, phased budgets, and vendor exit strategies baked in.',
            'category' => 'ICT Consultancy',
            'category_color' => '#7c3aed',
            'date' => '2026-03-02',
            'reading_minutes' => 8,
            'image' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600082/modern-data-center-providing-cloud-services-enabling-businesses-access-computing-resources-storage-demand-internet-server-room-infrastructure-3d-render-animation_lljtml.jpg',
            'paragraphs' => [
                'Sequence initiatives by dependency—not hype—to unlock incremental revenue.',
                'Pair each initiative with a finance steward who understands TZS cash cycles.',
                'Revisit quarterly; East African FX swings invalidate static five‑year decks quickly.',
            ],
        ],
    ],

    'portfolio_projects' => [
        [
            'slug' => 'kilimanjaro-summit-tours',
            'title' => 'Kilimanjaro Summit Tours',
            'tag' => 'Tour Website',
            'category' => 'web',
            'categoryLabel' => 'Web Platforms',
            'featured' => false,
            'excerpt' => 'Tour operator web platform with booking engine, multi-language content, and mobile money checkout tuned for international climbers.',
            'image' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600083/network-switch-with-cables_btxlxw.jpg',
            'highlights' => ['Multilingual UX', 'Booking & CRM hooks', 'Payments-ready architecture'],
            'stack' => ['Laravel', 'Livewire', 'M-Pesa APIs', 'AWS Cape Town region'],
            'duration' => '6 weeks',
            'clientLocation' => 'Moshi, Tanzania',
            'services' => ['Web Development', 'Booking Systems', 'Online Payments'],
            'impactSummary' => 'A single itinerary builder replaced fragmented spreadsheets, syncing reservations staff in Moshi while keeping Lighthouse scores healthy on 3G networks common at trailhead lodges.',
            'impact' => [
                ['value' => '40%', 'label' => 'Faster Booking'],
                ['value' => '4', 'label' => 'Languages Live'],
                ['value' => '99%', 'label' => 'Platform Uptime'],
                ['value' => '3G', 'label' => 'Optimised For Low Bandwidth'],
            ],
            'paragraphs' => [
                'We unified fragmented spreadsheets into a single itinerary builder that syncs with reservations staff in Moshi.',
                'Localized performance tuning keeps Lighthouse scores healthy on 3G networks common at trailhead lodges.',
                'Analytics pipelines expose campaign ROI across EU and North American audiences.',
            ],
        ],
        [
            'slug' => 'tanzania-crafts-store',
            'title' => 'Tanzania Crafts Store',
            'tag' => 'E-Commerce',
            'category' => 'web',
            'categoryLabel' => 'Web Platforms',
            'featured' => false,
            'excerpt' => 'Artisan marketplace featuring catalogue merchandising, fulfillment dashboards, and tiered shipping logic.',
            'image' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600084/i-m-hungry-hands-man-looking-food-delivery-app-his-smartphone-ordering-dinner-online_igrjev.jpg',
            'highlights' => ['Inventory accuracy', 'SMS confirmations', 'Vendor onboarding'],
            'stack' => ['WooCommerce', 'Flutter web wrappers', 'TigoPesa'],
            'duration' => '8 weeks',
            'clientLocation' => 'Dar es Salaam, Tanzania',
            'services' => ['Web Development', 'E-Commerce', 'SMS Integration'],
            'impactSummary' => 'QR-tagged batch metadata cut picking errors, automated SMS workflows notify cooperatives the moment payouts settle, and Swahili synonym search lifted product discovery.',
            'impact' => [
                ['value' => '99.2%', 'label' => 'Inventory Accuracy'],
                ['value' => '70%', 'label' => 'Fewer Picking Errors'],
                ['value' => '24h', 'label' => 'SMS Payout Alerts'],
                ['value' => '2×', 'label' => 'Repeat Order Rate'],
            ],
            'paragraphs' => [
                'Warehouse operators scan QR codes tied to batch metadata to reduce picking errors.',
                'Automated SMS workflows notify cooperatives when payouts settle.',
                'Elastic search indexes SwahiliSKU synonyms for better discovery.',
            ],
        ],
        [
            'slug' => 'swiftdeliver-app',
            'title' => 'SwiftDeliver Mobile',
            'tag' => 'Mobile App',
            'category' => 'mobile',
            'categoryLabel' => 'Mobile Applications',
            'featured' => false,
            'excerpt' => 'Cross-platform logistics app combining dispatcher dashboards, driver payouts, and GPS breadcrumbs.',
            'image' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600083/showing-cart-trolley-shopping-online-sign-graphic_j4fy9u.jpg',
            'highlights' => ['Realtime GPS', 'Driver wallets', 'Rating safeguards'],
            'stack' => ['Flutter', 'Firebase', 'Node.js'],
            'duration' => '10 weeks',
            'clientLocation' => 'Dar es Salaam, Tanzania',
            'services' => ['Mobile App Development', 'GPS Tracking', 'Payment Wallets'],
            'impactSummary' => 'Trip batching deduplicates overlapping deliveries across Kinondoni and Ubungo hubs, offline caching keeps proof-of-delivery capture working in tunnels and basements, and risk scoring flags suspicious refunds before finance approves.',
            'impact' => [
                ['value' => '35%', 'label' => 'Faster Deliveries'],
                ['value' => '1.2k+', 'label' => 'Daily Deliveries'],
                ['value' => '50%', 'label' => 'Fewer Failed Trips'],
                ['value' => '24/7', 'label' => 'Live Tracking'],
            ],
            'paragraphs' => [
                'Trip batches dedupe overlapping deliveries across Kinondoni and Ubungo hubs.',
                'Offline caching ensures POD captures survive tunnels and basements.',
                'Risk scoring flags suspicious refund attempts before finance approves.',
            ],
        ],
        [
            'slug' => 'serengeti-lodge-network',
            'title' => 'Serengeti Lodge Network',
            'tag' => 'Networking',
            'category' => 'ict',
            'categoryLabel' => 'ICT Solutions',
            'featured' => false,
            'excerpt' => 'Camp-wide Wi-Fi with guest VLANs, proactive monitoring, and failover LTE.',
            'image' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600079/beautiful-optical-fiber-detail_wck3wq.jpg',
            'highlights' => ['Multi-AP mesh', 'Guest segregation', 'SNMP dashboards'],
            'stack' => ['Ubiquiti', 'MikroTik', 'Zabbix'],
            'duration' => '4 weeks',
            'clientLocation' => 'Serengeti, Tanzania',
            'services' => ['Network Installation', 'Guest Wi-Fi', 'Monitoring'],
            'impactSummary' => 'Predictive surveys placed APs around mess tents and spa facilities, captive portals capture marketing consent while limiting bandwidth hogs, and automated WhatsApp alerts escalate the moment WAN latency spikes.',
            'impact' => [
                ['value' => '100%', 'label' => 'Camp Coverage'],
                ['value' => '99.9%', 'label' => 'Wi-Fi Uptime'],
                ['value' => '8', 'label' => 'Camps Connected'],
                ['value' => '10×', 'label' => 'Faster Roaming'],
            ],
            'paragraphs' => [
                'Predictive surveys informed AP placement around mess tents and spa facilities.',
                'Captive portal integrations capture marketing consent while limiting bandwidth hogs.',
                'Automated alerts escalate via WhatsApp when WAN latency spikes.',
            ],
        ],
        [
            'slug' => 'hotel-security-audit',
            'title' => 'Hotel Security Audit Program',
            'tag' => 'Cybersecurity',
            'category' => 'ict',
            'categoryLabel' => 'ICT Solutions',
            'featured' => false,
            'excerpt' => 'Purple-team style assessments covering POS segmentation, Active Directory hygiene, and incident tabletop drills.',
            'image' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600081/criminal-hacking-system-unsuccessfully_jjxzdq.jpg',
            'highlights' => ['POS isolation', 'IAM cleanup', 'Executive reporting'],
            'stack' => ['Qualys', 'Wazuh', 'MITRE ATT&CK mappings'],
            'duration' => '3 weeks',
            'clientLocation' => 'Arusha, Tanzania',
            'services' => ['Cybersecurity', 'Security Audits', 'Compliance'],
            'impactSummary' => 'Legacy RDP exposure on housekeeping tablets was remediated within 48 hours, findings aligned with TCRA guidance for hospitality chains, and a monthly retainer keeps drift monitored post-remediation.',
            'impact' => [
                ['value' => '48h', 'label' => 'Critical Remediation'],
                ['value' => '0', 'label' => 'Breaches Since'],
                ['value' => '100%', 'label' => 'POS Isolation'],
                ['value' => '90%', 'label' => 'Faster Compliance'],
            ],
            'paragraphs' => [
                'Discovered legacy RDP exposure on housekeeping tablets—remediated within 48 hours.',
                'Aligned findings with TCRA cyber incident guidance for hospitality chains.',
                'Monthly retainer keeps drift monitored post-remediation.',
            ],
        ],
        [
            'slug' => 'precision-air-supplier',
            'title' => 'Precision Air Supplier Portal',
            'tag' => 'Web Development',
            'category' => 'systems',
            'categoryLabel' => 'Software Systems',
            'featured' => true,
            'excerpt' => 'Corporate procurement portal with RFQ workflows, document versioning, and SLA dashboards.',
            'image' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600082/modern-data-center-providing-cloud-services-enabling-businesses-access-computing-resources-storage-demand-internet-server-room-infrastructure-3d-render-animation_lljtml.jpg',
            'highlights' => ['Role-based access', 'Audit trails', 'Executive KPIs'],
            'stack' => ['Laravel', 'Vue.js', 'PostgreSQL'],
            'duration' => '12 weeks',
            'clientLocation' => 'Dar es Salaam, Tanzania',
            'services' => ['System Development', 'Web Development', 'ERP Integrations'],
            'impactSummary' => 'Digitized supplier onboarding cut approval cycles from weeks to days, executive dashboards highlight fulfillment risk before aircraft maintenance windows, and ERP hooks eliminate duplicate master data entry.',
            'impact' => [
                ['value' => 'Weeks→Days', 'label' => 'Approval Cycles'],
                ['value' => '100%', 'label' => 'Audit Trail'],
                ['value' => '40%', 'label' => 'Faster Procurement'],
                ['value' => '24/7', 'label' => 'Portal Availability'],
            ],
            'paragraphs' => [
                'Digitized supplier onboarding cut approval cycles from weeks to days.',
                'Executive dashboards highlight fulfillment risk before aircraft maintenance windows.',
                'Integration hooks feed ERP without duplicate master data entry.',
            ],
        ],
        [
            'slug' => 'moshi-smart-campus-wifi',
            'title' => 'Moshi Smart Campus Wi-Fi',
            'tag' => 'Networking',
            'category' => 'ict',
            'categoryLabel' => 'ICT Solutions',
            'featured' => false,
            'excerpt' => 'Education campus network refresh with BYOD policies, classroom shaping, and safeguarding filters.',
            'image' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600083/network-switch-with-cables_btxlxw.jpg',
            'highlights' => ['Policy enforcement', 'Bandwidth fairness', 'Teacher VLANs'],
            'stack' => ['Aruba Instant', 'FortiGate', '802.1X'],
            'duration' => '5 weeks',
            'clientLocation' => 'Moshi, Tanzania',
            'services' => ['Network Installation', 'Wi-Fi Solutions', 'Security Configuration'],
            'impactSummary' => 'Student devices were separated from examination labs to prevent multicast storms, parent portals expose uptime commitments transparently, and nightly controller config backups minimize exam-week surprises.',
            'impact' => [
                ['value' => '3,000+', 'label' => 'Students Connected'],
                ['value' => '99.5%', 'label' => 'Network Uptime'],
                ['value' => '15m', 'label' => 'Issue Resolution'],
                ['value' => '100%', 'label' => 'Safeguarding Filters'],
            ],
            'paragraphs' => [
                'Separated student devices from examination labs to prevent multicast storms.',
                'Parent portals expose uptime commitments transparently.',
                'Nightly backups of controller configs minimize exam-week surprises.',
            ],
        ],
        [
            'slug' => 'ngo-cloud-migration',
            'title' => 'Regional NGO Cloud Migration',
            'tag' => 'Cloud Services',
            'category' => 'digital',
            'categoryLabel' => 'Digital Platforms',
            'featured' => false,
            'excerpt' => 'Lift-and-refactor of donor reporting stacks into resilient cloud landing zones with FinOps guardrails.',
            'image' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600082/modern-data-center-providing-cloud-services-enabling-businesses-access-computing-resources-storage-demand-internet-server-room-infrastructure-3d-render-animation_lljtml.jpg',
            'highlights' => ['Cost guardrails', 'Disaster recovery', 'IAM modernization'],
            'stack' => ['AWS Organizations', 'Terraform', 'Azure AD'],
            'duration' => '8 weeks',
            'clientLocation' => 'East Africa (Regional)',
            'services' => ['Cloud Services', 'DevOps', 'Security & Compliance'],
            'impactSummary' => 'Sandbox accounts per country program enable safer experimentation, automated savings plans trimmed burn by 28% within two quarters, and cross-border replication satisfies donor DR expectations.',
            'impact' => [
                ['value' => '28%', 'label' => 'Cost Reduction'],
                ['value' => '99.9%', 'label' => 'Availability'],
                ['value' => '100%', 'label' => 'Donor Compliance'],
                ['value' => '5', 'label' => 'Countries Live'],
            ],
            'paragraphs' => [
                'Defined sandbox accounts per country program for safer experimentation.',
                'Automated savings plans trimmed burn by 28% within two quarters.',
                'Cross-border replication satisfies donor DR expectations.',
            ],
        ],
    ],
    'team_stats' => [
        ['value' => '10', 'suffix' => '+', 'label' => 'Professionals'],
        ['value' => '8', 'suffix' => '+', 'label' => 'Technology Areas'],
        ['value' => '50', 'suffix' => '+', 'label' => 'Projects Delivered'],
        ['value' => '24', 'suffix' => '/7', 'label' => 'Digital Support'],
    ],
    'service_card_images' => [
        'Web Development' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600083/programming-background-with-person-working-with-codes-computer_f8umdv.jpg',
        'E-commerce Solutions' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600083/programming-background-with-person-working-with-codes-computer_f8umdv.jpg',
        'E-Commerce & Online Stores' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600083/programming-background-with-person-working-with-codes-computer_f8umdv.jpg',
        'Corporate Websites' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600083/programming-background-with-person-working-with-codes-computer_f8umdv.jpg',
        'Web Applications' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600083/programming-background-with-person-working-with-codes-computer_f8umdv.jpg',
        'SEO Services' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600083/programming-background-with-person-working-with-codes-computer_f8umdv.jpg',
        'CMS Development' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600082/programmer-home-office-concentrating-finding-bugs-while-he-codes_gctbqc.jpg',
        'UI/UX Design' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600082/programmer-home-office-concentrating-finding-bugs-while-he-codes_gctbqc.jpg',
        'Mobile App Development' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600084/i-m-hungry-hands-man-looking-food-delivery-app-his-smartphone-ordering-dinner-online_igrjev.jpg',
        'E-commerce Apps' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600084/i-m-hungry-hands-man-looking-food-delivery-app-his-smartphone-ordering-dinner-online_igrjev.jpg',
        'Delivery & Booking Apps' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600084/i-m-hungry-hands-man-looking-food-delivery-app-his-smartphone-ordering-dinner-online_igrjev.jpg',
        'Business Apps' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600084/i-m-hungry-hands-man-looking-food-delivery-app-his-smartphone-ordering-dinner-online_igrjev.jpg',
        'Delivery & Tracking' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600084/i-m-hungry-hands-man-looking-food-delivery-app-his-smartphone-ordering-dinner-online_igrjev.jpg',
        'Healthcare Apps' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600084/i-m-hungry-hands-man-looking-food-delivery-app-his-smartphone-ordering-dinner-online_igrjev.jpg',
        'Gaming & Entertainment' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600084/i-m-hungry-hands-man-looking-food-delivery-app-his-smartphone-ordering-dinner-online_igrjev.jpg',
        'Network Installation' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600083/network-switch-with-cables_btxlxw.jpg',
        'Network & CCTV Security' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600083/network-switch-with-cables_btxlxw.jpg',
        'CCTV & Security Systems' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600083/network-switch-with-cables_btxlxw.jpg',
        'Network Design' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600083/network-switch-with-cables_btxlxw.jpg',
        'Network Maintenance' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600083/network-switch-with-cables_btxlxw.jpg',
        'Wireless Solutions' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600083/network-switch-with-cables_btxlxw.jpg',
        'Network Optimization' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600083/network-switch-with-cables_btxlxw.jpg',
        'Network Security' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600081/criminal-hacking-system-unsuccessfully_jjxzdq.jpg',
        'Cybersecurity' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600081/criminal-hacking-system-unsuccessfully_jjxzdq.jpg',
        'Security Assessment' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600081/criminal-hacking-system-unsuccessfully_jjxzdq.jpg',
        'Data Protection' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600081/criminal-hacking-system-unsuccessfully_jjxzdq.jpg',
        'Compliance Management' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600081/criminal-hacking-system-unsuccessfully_jjxzdq.jpg',
        'Security Monitoring' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600081/criminal-hacking-system-unsuccessfully_jjxzdq.jpg',
        'Incident Response' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600081/criminal-hacking-system-unsuccessfully_jjxzdq.jpg',
        'Security Services' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600081/criminal-hacking-system-unsuccessfully_jjxzdq.jpg',
        'Compliance & Risk' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600081/criminal-hacking-system-unsuccessfully_jjxzdq.jpg',
        'Cloud Security' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600081/criminal-hacking-system-unsuccessfully_jjxzdq.jpg',
        'IT Support' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600081/portrait-male-engineer-working-field-engineers-day-celebration_afzsch.jpg',
        'Remote Support' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600081/portrait-male-engineer-working-field-engineers-day-celebration_afzsch.jpg',
        'On-site Service' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600081/portrait-male-engineer-working-field-engineers-day-celebration_afzsch.jpg',
        'Maintenance' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600081/portrait-male-engineer-working-field-engineers-day-celebration_afzsch.jpg',
        'ICT Consultancy' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600083/engineer-coworkers-server-farm-checking-recovery-plan_blibxz.jpg',
        'Digital Strategy' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600083/engineer-coworkers-server-farm-checking-recovery-plan_blibxz.jpg',
        'Technology Planning' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600083/engineer-coworkers-server-farm-checking-recovery-plan_blibxz.jpg',
        'Consulting' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600083/engineer-coworkers-server-farm-checking-recovery-plan_blibxz.jpg',
        'Cloud Consulting' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600083/engineer-coworkers-server-farm-checking-recovery-plan_blibxz.jpg',
        'System Development' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600080/data-center-programmers-doing-brainstorming-setting-up-machine-learning-systems_ggwvwd.jpg',
        'Business Automation' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600080/data-center-programmers-doing-brainstorming-setting-up-machine-learning-systems_ggwvwd.jpg',
        'Process Optimization' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600080/data-center-programmers-doing-brainstorming-setting-up-machine-learning-systems_ggwvwd.jpg',
        'Performance Analytics' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600080/data-center-programmers-doing-brainstorming-setting-up-machine-learning-systems_ggwvwd.jpg',
        'ERP Development' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600080/data-center-programmers-doing-brainstorming-setting-up-machine-learning-systems_ggwvwd.jpg',
        'CRM Development' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600080/data-center-programmers-doing-brainstorming-setting-up-machine-learning-systems_ggwvwd.jpg',
        'Inventory Management' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600080/data-center-programmers-doing-brainstorming-setting-up-machine-learning-systems_ggwvwd.jpg',
        'Custom Solutions' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600080/data-center-programmers-doing-brainstorming-setting-up-machine-learning-systems_ggwvwd.jpg',
        'HR Management' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600078/admin-data-center-typing-notebook-keyboard-using-automation-tools_lsc29m.jpg',
        'Cloud Services' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600082/modern-data-center-providing-cloud-services-enabling-businesses-access-computing-resources-storage-demand-internet-server-room-infrastructure-3d-render-animation_lljtml.jpg',
        'Cloud & Data Protection' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600082/modern-data-center-providing-cloud-services-enabling-businesses-access-computing-resources-storage-demand-internet-server-room-infrastructure-3d-render-animation_lljtml.jpg',
        'Cloud Migration' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600082/modern-data-center-providing-cloud-services-enabling-businesses-access-computing-resources-storage-demand-internet-server-room-infrastructure-3d-render-animation_lljtml.jpg',
        'Cloud Storage' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600082/modern-data-center-providing-cloud-services-enabling-businesses-access-computing-resources-storage-demand-internet-server-room-infrastructure-3d-render-animation_lljtml.jpg',
        'Cloud Computing' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600082/modern-data-center-providing-cloud-services-enabling-businesses-access-computing-resources-storage-demand-internet-server-room-infrastructure-3d-render-animation_lljtml.jpg',
        'Cloud Backup' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600082/modern-data-center-providing-cloud-services-enabling-businesses-access-computing-resources-storage-demand-internet-server-room-infrastructure-3d-render-animation_lljtml.jpg',
        'Accounting Software' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600081/african-american-advisor-reviewing-legal-balance-desk-green-screen_qmcihs.jpg',
        'Accounting System Setup' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600078/admin-data-center-typing-notebook-keyboard-using-automation-tools_lsc29m.jpg',
        'Bookkeeping' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600081/african-american-advisor-reviewing-legal-balance-desk-green-screen_qmcihs.jpg',
        'Financial Reporting' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600081/african-american-advisor-reviewing-legal-balance-desk-green-screen_qmcihs.jpg',
        'Payroll Services' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600081/african-american-advisor-reviewing-legal-balance-desk-green-screen_qmcihs.jpg',
        'Tax Support' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600081/african-american-advisor-reviewing-legal-balance-desk-green-screen_qmcihs.jpg',
        'Accounts Preparation' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600081/african-american-advisor-reviewing-legal-balance-desk-green-screen_qmcihs.jpg',
        'Financial Analysis' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600081/african-american-advisor-reviewing-legal-balance-desk-green-screen_qmcihs.jpg',
        'Budgeting & Planning' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600081/african-american-advisor-reviewing-legal-balance-desk-green-screen_qmcihs.jpg',
        'Management Accounting' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600081/african-american-advisor-reviewing-legal-balance-desk-green-screen_qmcihs.jpg',
        'Business Financial Advisory' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600081/african-american-advisor-reviewing-legal-balance-desk-green-screen_qmcihs.jpg',
        'Financial Systems' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600081/african-american-advisor-reviewing-legal-balance-desk-green-screen_qmcihs.jpg',
        'Security Training' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600085/teamworking-engineers-talking-server-room-doing-brainstorming_vm01lf.jpg',
        'Training & Development' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600085/teamworking-engineers-talking-server-room-doing-brainstorming_vm01lf.jpg',
        'Educational Apps' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600085/teamworking-engineers-talking-server-room-doing-brainstorming_vm01lf.jpg',
    ],
];
