<?php

return [
    'blog_posts' => [
        [
            'slug' => 'web-development-trends-tanzania-2026',
            'title' => 'Top Web Development Trends for Tanzanian Businesses in 2026',
            'excerpt' => 'Composable stacks, performance budgets, and mobile-money-first UX are reshaping how East African brands ship digital products.',
            'category' => 'Web Development',
            'category_color' => '#1a6fc4',
            'date' => '2026-05-02',
            'reading_minutes' => 7,
            'image' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600083/programming-background-with-person-working-with-codes-computer_f8umdv.jpg',
            'paragraphs' => [
                'Teams across Tanzania are prioritizing Lighthouse performance, structured content models, and resilient hosting footprints that survive intermittent connectivity.',
                'Mobile money remains the conversion backbone—checkout flows that preload operators (M‑Pesa, TigoPesa, AzamPesa) and expose deep links reduce abandoned carts dramatically.',
                'Composable architectures let marketers iterate without redeploying the entire stack, keeping safari operators agile during seasonality spikes.',
            ],
        ],
        [
            'slug' => 'cyber-threat-landscape-tz-smes',
            'title' => 'How SMEs in Tanzania Should Prioritize Cyber Defense',
            'excerpt' => 'Start with asset inventory, segmented Wi‑Fi, and realistic tabletop exercises before chasing shiny tools.',
            'category' => 'Cybersecurity',
            'category_color' => '#dc2626',
            'date' => '2026-04-28',
            'reading_minutes' => 6,
            'image' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600081/criminal-hacking-system-unsuccessfully_jjxzdq.jpg',
            'paragraphs' => [
                'Most breaches we remediate still stem from reused VPN passwords and flat networks—fix segmentation before buying another appliance.',
                'Weekly backups tested via restores outperform glossy “immutable” marketing slides when ransomware strikes at month-end closing.',
                'Align monitoring alerts to business hours in East Africa Time so on-call rotations stay humane while staying compliant with regulator expectations.',
            ],
        ],
        [
            'slug' => 'hospitality-network-design-best-practices',
            'title' => 'Designing Guest‑Grade Networks for Lodges & Camps',
            'excerpt' => 'Separate VLANs, captive portals, and proactive RF surveys keep hospitality brands review‑worthy.',
            'category' => 'Networking',
            'category_color' => '#10b981',
            'date' => '2026-04-22',
            'reading_minutes' => 8,
            'image' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600083/network-switch-with-cables_btxlxw.jpg',
            'paragraphs' => [
                'Start every engagement with a predictive survey—not guesswork—especially when stone walls and safari tents skew attenuation.',
                'Guest SSIDs should never share broadcast domains with POS or CCTV backhauls; micro‑segmentation saves incident response time.',
                'Automated SMS alerts on WAN failover mean lodge managers wake up to actionable context instead of angry TripAdvisor screenshots.',
            ],
        ],
        [
            'slug' => 'mobile-apps-customer-retention-2026',
            'title' => 'Why Tanzanian Brands Win Retention with Mobile Apps',
            'excerpt' => 'Offline caches, proactive push journeys, and ledger‑grade payments anchor loyalty beyond landing pages.',
            'category' => 'Mobile Apps',
            'category_color' => '#8b5cf6',
            'date' => '2026-04-18',
            'reading_minutes' => 5,
            'image' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600084/i-m-hungry-hands-man-looking-food-delivery-app-his-smartphone-ordering-dinner-online_igrjev.jpg',
            'paragraphs' => [
                'Flutter and React Native parity cuts dual‑team overhead while keeping parity with platform‑specific payment SDK expectations.',
                'Behavioral cohorts powered by local SMS gateways outperform expensive foreign ESPs when bandwidth budgets are tight.',
                'Ship incremental releases tied to analytics experiments—not yearly big bangs—to learn from Dar es Salaam and Arusha cohort differences.',
            ],
        ],
        [
            'slug' => 'cloud-cost-controls-tanzanian-smes',
            'title' => 'Cloud Economics: Rightsizing Workloads for Tanzanian SMEs',
            'excerpt' => 'Reserved capacity, egress discipline, and tagging hygiene beat generic lift‑and‑shift quotes.',
            'category' => 'Cloud Services',
            'category_color' => '#3b82f6',
            'date' => '2026-04-12',
            'reading_minutes' => 6,
            'image' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600082/modern-data-center-providing-cloud-services-enabling-businesses-access-computing-resources-storage-demand-internet-server-room-infrastructure-3d-render-animation_lljtml.jpg',
            'paragraphs' => [
                'Finance teams want amortization clarity—tie each cloud invoice line to a department tag before auditors ask.',
                'Burst workloads belong on serverless hooks; steady ERP replicas deserve predictable VMs with backup snapshots cross‑region.',
                'Monthly checkpoints comparing USD invoices against TZS budgets avoid unpleasant FX surprises.',
            ],
        ],
        [
            'slug' => 'proactive-it-support-playbook',
            'title' => 'Proactive IT Support Beats Break‑Fix Every Time',
            'excerpt' => 'Telemetry on endpoints, patch calendars, and WhatsApp bridges shorten MTTR for distributed teams.',
            'category' => 'IT Support',
            'category_color' => '#f59e0b',
            'date' => '2026-04-09',
            'reading_minutes' => 5,
            'image' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600078/admin-data-center-typing-notebook-keyboard-using-automation-tools_lsc29m.jpg',
            'paragraphs' => [
                'Automated patching windows aligned with payroll deadlines reduce helpdesk chaos.',
                'SMS‑first ticketing respects how NGO field teams actually collaborate.',
                'Quarterly resilience drills simulate ISP outages so failover routes stay warm—not theoretical.',
            ],
        ],
        [
            'slug' => 'mpesa-api-integration-checklist',
            'title' => 'Checklist: Shipping Reliable Mobile Money APIs',
            'excerpt' => 'Idempotency keys, reconciliation jobs, and sandbox parity save launch weekends.',
            'category' => 'Web Development',
            'category_color' => '#1a6fc4',
            'date' => '2026-04-05',
            'reading_minutes' => 7,
            'image' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600083/showing-cart-trolley-shopping-online-sign-graphic_j4fy9u.jpg',
            'paragraphs' => [
                'Webhook retries must be deduplicated—store gateway references with unique indexes.',
                'User‑visible failures deserve Swahili microcopy plus WhatsApp escalation paths.',
                'Nightly reconciliation spreadsheets are not optional when regulators request audit trails.',
            ],
        ],
        [
            'slug' => 'data-sovereignty-east-africa',
            'title' => 'Data Sovereignty Conversations Every CTO Should Own',
            'excerpt' => 'Understand residency commitments, subprocessors, and encryption scopes before signing SaaS agreements.',
            'category' => 'ICT Strategy',
            'category_color' => '#0f766e',
            'date' => '2026-03-30',
            'reading_minutes' => 6,
            'image' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600082/modern-data-center-providing-cloud-services-enabling-businesses-access-computing-resources-storage-demand-internet-server-room-infrastructure-3d-render-animation_lljtml.jpg',
            'paragraphs' => [
                'Map regulated datasets (payroll, health, telco metadata) to concrete storage regions—not marketing PDFs.',
                'Bring legal and infra leads into the same workshop; ambiguous DPAs become operational runbooks.',
                'Document breach notification timelines in EAT to avoid scrambling during holidays.',
            ],
        ],
        [
            'slug' => 'wifi-security-for-remote-teams',
            'title' => 'Securing Home Wi‑Fi for Distributed Tanzanian Teams',
            'excerpt' => 'Hardware swaps, WPA3, and DNS filtering raise the floor against credential stuffing.',
            'category' => 'Cybersecurity',
            'category_color' => '#dc2626',
            'date' => '2026-03-24',
            'reading_minutes' => 4,
            'image' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600083/network-switch-with-cables_btxlxw.jpg',
            'paragraphs' => [
                'Issue corporate VPN profiles instead of trusting residential ISP routers blindly.',
                'DNS filtering blocks phishing kits targeting payroll portals common during bonus season.',
                'Quarterly reminders to rotate IoT passwords prevent Mirai‑style noise from impacting Zoom calls.',
            ],
        ],
        [
            'slug' => 'analytics-for-tour-operators',
            'title' => 'Analytics Dashboards Tour Operators Actually Use',
            'excerpt' => 'Connect CRM stages, ad spend, and mobile money settlements into one nightly rollup.',
            'category' => 'Data & Analytics',
            'category_color' => '#ea580c',
            'date' => '2026-03-18',
            'reading_minutes' => 6,
            'image' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600083/programming-background-with-person-working-with-codes-computer_f8umdv.jpg',
            'paragraphs' => [
                'Stop exporting CSVs manually—schedule transforms into Looker or Metabase with TZ timezone baked in.',
                'Attribute conversions back to WhatsApp threads using UTMs embedded in wa.me links.',
                'Alert teams when cost‑per‑lead spikes post‑algorithm updates.',
            ],
        ],
        [
            'slug' => 'iot-sensors-field-operations',
            'title' => 'IoT Telemetry Without Overengineering Your Stack',
            'excerpt' => 'MQTT brokers at the edge plus lightweight dashboards beat premature Kubernetes clusters.',
            'category' => 'Networking',
            'category_color' => '#10b981',
            'date' => '2026-03-10',
            'reading_minutes' => 5,
            'image' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600079/beautiful-optical-fiber-detail_wck3wq.jpg',
            'paragraphs' => [
                'Battery‑powered sensors need solar failover plans documented ahead of rainy seasons.',
                'Backhaul over LTE? negotiate QoS with carriers before deploying hundreds of nodes.',
                'Use Grafana alerts routed to SMS when WAN latency crosses SLA thresholds.',
            ],
        ],
        [
            'slug' => 'digital-transformation-roadmaps',
            'title' => 'Building ICT Roadmaps Leadership Will Fund',
            'excerpt' => 'Start with measurable KPIs, phased budgets, and vendor exit strategies baked in.',
            'category' => 'ICT Consultancy',
            'category_color' => '#7c3aed',
            'date' => '2026-03-02',
            'reading_minutes' => 8,
            'image' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600082/modern-data-center-providing-cloud-services-enabling-businesses-access-computing-resources-storage-demand-internet-server-room-infrastructure-3d-render-animation_lljtml.jpg',
            'paragraphs' => [
                'Sequence initiatives by dependency—not hype—to unlock incremental revenue.',
                'Pair each initiative with a finance steward who understands TZS cash cycles.',
                'Revisit quarterly; East African FX swings invalidate static five‑year decks quickly.',
            ],
        ],
    ],

    'portfolio_projects' => [
        [
            'slug' => 'kilimanjaro-summit-tours',
            'title' => 'Kilimanjaro Summit Tours',
            'tag' => 'Tour Website',
            'excerpt' => 'Tour operator web platform with booking engine, multi-language content, and mobile money checkout tuned for international climbers.',
            'image' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600083/network-switch-with-cables_btxlxw.jpg',
            'highlights' => ['Multilingual UX', 'Booking & CRM hooks', 'Payments-ready architecture'],
            'stack' => ['Laravel', 'Livewire', 'M‑Pesa APIs', 'AWS Cape Town region'],
            'paragraphs' => [
                'We unified fragmented spreadsheets into a single itinerary builder that syncs with reservations staff in Moshi.',
                'Localized performance tuning keeps Lighthouse scores healthy on 3G networks common at trailhead lodges.',
                'Analytics pipelines expose campaign ROI across EU and North American audiences.',
            ],
        ],
        [
            'slug' => 'tanzania-crafts-store',
            'title' => 'Tanzania Crafts Store',
            'tag' => 'E-Commerce',
            'excerpt' => 'Artisan marketplace featuring catalogue merchandising, fulfillment dashboards, and tiered shipping logic.',
            'image' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600084/i-m-hungry-hands-man-looking-food-delivery-app-his-smartphone-ordering-dinner-online_igrjev.jpg',
            'highlights' => ['Inventory accuracy', 'SMS confirmations', 'Vendor onboarding'],
            'stack' => ['WooCommerce', 'Flutter web wrappers', 'TigoPesa'],
            'paragraphs' => [
                'Warehouse operators scan QR codes tied to batch metadata to reduce picking errors.',
                'Automated SMS workflows notify cooperatives when payouts settle.',
                'Elastic search indexes SwahiliSKU synonyms for better discovery.',
            ],
        ],
        [
            'slug' => 'swiftdeliver-app',
            'title' => 'SwiftDeliver Mobile',
            'tag' => 'Mobile App',
            'excerpt' => 'Cross-platform logistics app combining dispatcher dashboards, driver payouts, and GPS breadcrumbs.',
            'image' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600083/showing-cart-trolley-shopping-online-sign-graphic_j4fy9u.jpg',
            'highlights' => ['Realtime GPS', 'Driver wallets', 'Rating safeguards'],
            'stack' => ['Flutter', 'Firebase', 'Node.js'],
            'paragraphs' => [
                'Trip batches dedupe overlapping deliveries across Kinondoni and Ubungo hubs.',
                'Offline caching ensures POD captures survive tunnels and basements.',
                'Risk scoring flags suspicious refund attempts before finance approves.',
            ],
        ],
        [
            'slug' => 'serengeti-lodge-network',
            'title' => 'Serengeti Lodge Network',
            'tag' => 'Networking',
            'excerpt' => 'Camp-wide Wi‑Fi with guest VLANs, proactive monitoring, and failover LTE.',
            'image' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600079/beautiful-optical-fiber-detail_wck3wq.jpg',
            'highlights' => ['Multi-AP mesh', 'Guest segregation', 'SNMP dashboards'],
            'stack' => ['Ubiquiti', 'MikroTik', 'Zabbix'],
            'paragraphs' => [
                'Predictive surveys informed AP placement around mess tents and spa facilities.',
                'Captive portal integrations capture marketing consent while limiting bandwidth hogs.',
                'Automated alerts escalate via WhatsApp when WAN latency spikes.',
            ],
        ],
        [
            'slug' => 'hotel-security-audit',
            'title' => 'Hotel Security Audit Program',
            'tag' => 'Cybersecurity',
            'excerpt' => 'Purple-team style assessments covering POS segmentation, Active Directory hygiene, and incident tabletop drills.',
            'image' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600081/criminal-hacking-system-unsuccessfully_jjxzdq.jpg',
            'highlights' => ['POS isolation', 'IAM cleanup', 'Executive reporting'],
            'stack' => ['Qualys', 'Wazuh', 'MITRE ATT&CK mappings'],
            'paragraphs' => [
                'Discovered legacy RDP exposure on housekeeping tablets—remediated within 48 hours.',
                'Aligned findings with TCRA cyber incident guidance for hospitality chains.',
                'Monthly retainer keeps drift monitored post-remediation.',
            ],
        ],
        [
            'slug' => 'precision-air-supplier',
            'title' => 'Precision Air Supplier Portal',
            'tag' => 'Web Development',
            'excerpt' => 'Corporate procurement portal with RFQ workflows, document versioning, and SLA dashboards.',
            'image' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600082/modern-data-center-providing-cloud-services-enabling-businesses-access-computing-resources-storage-demand-internet-server-room-infrastructure-3d-render-animation_lljtml.jpg',
            'highlights' => ['Role-based access', 'Audit trails', 'Executive KPIs'],
            'stack' => ['Laravel', 'Vue.js', 'PostgreSQL'],
            'paragraphs' => [
                'Digitized supplier onboarding cut approval cycles from weeks to days.',
                'Executive dashboards highlight fulfillment risk before aircraft maintenance windows.',
                'Integration hooks feed ERP without duplicate master data entry.',
            ],
        ],
        [
            'slug' => 'moshi-smart-campus-wifi',
            'title' => 'Moshi Smart Campus Wi‑Fi',
            'tag' => 'Networking',
            'excerpt' => 'Education campus network refresh with BYOD policies, classroom shaping, and safeguarding filters.',
            'image' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600083/network-switch-with-cables_btxlxw.jpg',
            'highlights' => ['Policy enforcement', 'Bandwidth fairness', 'Teacher VLANs'],
            'stack' => ['Aruba Instant', 'FortiGate', '802.1X'],
            'paragraphs' => [
                'Separated student devices from examination labs to prevent multicast storms.',
                'Parent portals expose uptime commitments transparently.',
                'Nightly backups of controller configs minimize exam-week surprises.',
            ],
        ],
        [
            'slug' => 'ngo-cloud-migration',
            'title' => 'Regional NGO Cloud Migration',
            'tag' => 'Cloud Services',
            'excerpt' => 'Lift-and-refactor of donor reporting stacks into resilient cloud landing zones with FinOps guardrails.',
            'image' => 'https://res.cloudinary.com/dtxdrmjlk/image/upload/v1774600082/modern-data-center-providing-cloud-services-enabling-businesses-access-computing-resources-storage-demand-internet-server-room-infrastructure-3d-render-animation_lljtml.jpg',
            'highlights' => ['Cost guardrails', 'Disaster recovery', 'IAM modernization'],
            'stack' => ['AWS Organizations', 'Terraform', 'Azure AD'],
            'paragraphs' => [
                'Defined sandbox accounts per country program for safer experimentation.',
                'Automated savings plans trimmed burn by 28% within two quarters.',
                'Cross-border replication satisfies donor DR expectations.',
            ],
        ],
    ],
];
